teleop_node:
  ros__parameters:
    axis_linear:
      x: 1       # joystick axis for forward/backward (linear x)
      y: 2       # joystick axis for left/right (linear y)
    scale_linear:
      x: 0.363
      y: 0.363     # scale for linear y
    scale_linear_turbo:
      x: 1.0
      y: 1.0     # turbo scale for linear y

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.165
    scale_angular_turbo:
      yaw: 2.0

    enable_button: 8
    turbo_button: 9
    require_enable_button: true
