twist_mux:
  ros__parameters:

    use_stamped: false

    topics:
      tracker:
        topic   : cmd_vel_tracking
        timeout : 0.5
        priority: 20

      joystick:
        topic   : cmd_vel_joy
        timeout : 3.0
        priority: 100